version: 2
jobs:
  deploy-job:
    machine:
      enabled: true
    working_directory: ~/StaticWebExample
    steps:
      - checkout
      - run:
          name: Sync contents to S3
          command: aws s3 sync www/ s3://labks-staticweb --delete
workflows:
  version: 2
  deploy-contents:
    jobs:
      - deploy-job